### ISSUE TITLE
Need to set GO_PKG_PATH to build the app in tsuru

### ISSUE THREAD

**Issue by JulioCBLima** [tsuru/tsuru-autoscale#9]
When trying to deploy the app to tsuru the following error occours:
```
$ tsuru app-deploy -a autoscale .
Uploading files (1.35MB)... 100.00% Processing ok
/bin/sh: 27: source: not found
go version go1.8.3 linux/amd64
go version go1.8.3 linux/amd64
Installing Go stable...
# current
./main.go:31: cannot use apiRouter (type *"current/vendor/github.com/gorilla/mux".Router) as type *"github.com/tsuru/tsuru-autoscale/vendor/github.com/gorilla/mux".Router in argument to api.Router
./main.go:33: cannot use webRouter (type *"current/vendor/github.com/gorilla/mux".Router) as type *"github.com/tsuru/tsuru-autoscale/vendor/github.com/gorilla/mux".Router in argument to web.Router
error running "/var/lib/tsuru/deploy archive file:///home/application/archive.tar.gz": exit status 2
Exit status 1
```

It appears to be a vendor dependency error, like [this one](https://github.com/Masterminds/glide/issues/73).

Locally the build works if it's done inside the `$GOPATH/src/github.com/tsuru/tsuru-autoscale/` directory and get the same error if outside.

I was able to complete the build in tsuru by setting the `GO_PKG_PATH` env var to `github.com/tsuru/tsuru-autoscale` and then running the app-deploy.

**Comment by ggarnier** [comment]
This is a detail from tsuru Go platform, check the docs for more details:

https://docs.tsuru.io/stable/using/go.html#handling-dependencies
